#!/bin/sh
echo "Performing jslint check on all js resources"
find ./modules -name '*.js' -and ! -path '*isomorphic*' \
-and ! -path '*qunit*' -and ! -path '*docs*' \
-and ! -path '*LAB*' -and ! -path '*benchmark*' \
-and ! -path '*smartclient*' \
-and ! -path '*scopeleaks*' \
-and ! -path '*BigDecimal*' | xargs ./modules/org.openbravo.client.kernel/jslint/jslint || exit 1
