#!/bin/sh

# --browser doesn't work properly in jslint4java 1.4.7
# adding the global available functions manually: window, unscape, top, alert, escape
# adding globals present in qunit: ok, test, module, expect, same, stop, start, equals, asyncTest

echo "Checking --> $@"
java -jar ./modules/org.openbravo.client.kernel/lib/runtime/jslint4java-1.4.7.jar \
 --browser --evil --continue --undef \
 --predef window,unescape,escape,top,alert,isc,OB,ok,test,module,expect,same,stop,start,asyncTest,equals,BigDecimal "$@"
